export default {
    day: {
        background: '#F5F5F5',
        mainText: '#808080',
        backgroundList: '#FFFFFF',
        backgroundHeader: '#FFFFFF',
        textHeader: '#000000',
        backgroundButton: '#D3D3D3',
        hoverButton: '#A9A9A9',
        activeButton: '#000000',
        buttonText: '#000000',
        activeButtonText: '#FFFFFF',
        secondaryColor: 'black',
    },
    night: {
        background: '#',
        mainText: '#808080',
        backgroundList: '#',
        backgroundHeader: '#FFFFFF',
        textHeader: '#000000',
        backgroundButton: '#D3D3D3',
        hoverButton: '#A9A9A9',
        activeButton: '#000000',
        buttonText: '#FFFFFF',
        activeButtonText: '#000000',
        secondaryColor: 'black',
    },
};
